# Generated by Django 4.0.5 on 2022-07-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaluser',
            name='intetos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='intetos',
            field=models.IntegerField(default=0),
        ),
    ]
