# Generated by Django 4.0.5 on 2022-07-12 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_historicaluser_intetos_user_intetos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaluser',
            old_name='intetos',
            new_name='intentos',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='intetos',
            new_name='intentos',
        ),
    ]
